steps:
  build:
    when:
      branch: []
      event: [push, manual]
    image: registry.gitlab.com/islandoftex/images/texlive:latest
    commands:
      - make
    artifacts:
      paths:
        - ./build/*.pdf
